services:
  - type: web
    name: Courses
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn homepage:app"
    envVars:
  - key: SECRET_KEY
    sync: false
  - key: PAYPAL_CLIENT_ID
    sync: false
  - key: PAYPAL_SECRET
    sync: false
  - key: PAYPAL_API_BASE
    value: https://api-m.paypal.com
    sync: false
    healthCheckPath: /health

